import styles from './../styles/Home.module.scss';
import Head from "next/head";
import { SideBar } from "@/components/nav/SideBar";
import Header from "@/components/Header/Header";
import Hero from '@/components/Hero/Hero';
import About from '@/components/About/About';
import Projects from '@/components/projects/Projects';
import Experience from '@/components/experience/Experience';
import Contacts from '@/components/contacts/Contacts';

export default function Home() {
  return (
    <>
      <Head>
        <title>Попоудин Даниил | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/x-icon" href="/favicon.ico" />
      </Head>
      <div className={styles.grid}>
        <SideBar />
        <main>
          <Header/>
          <Hero/>
          <About/>
          <Projects/>
          <Experience/>
          <Contacts/>
        </main>
      </div>
    </>
  );
}
